# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Isa00seypf9pxqd-YRb7C_UnDbg1FRXT
"""

import requests

ip = input("Enter Crypto Currency : ")

ip = ip.upper()

resp = requests.get('https://www.cryptingup.com/api/markets')

r = resp.json()

coin = (r['markets'])

for i in coin:
  if i['exchange_id']==ip:
    print(i)

